from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from bma_standard_formulas.deals.schemas.ir import (
    AccountDef,
    AccountMinimumScheduleEntry,
    BondDef,
    CalculationNode,
    CollateralGroupDef,
    DealDefinition,
    FeeDef,
    RateScheduleEntry,
    RuleNode,
    TrancheRelation,
    TriggerNode,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "emit_field_order.py"
FIELD_ORDER_PATH = (
    REPO_ROOT
    / "src"
    / "bma_standard_formulas"
    / "deals"
    / "schemas"
    / "field_order.json"
)


def _run_emitter(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), *args],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )


def test_emitter_walks_all_nested_models_and_records_declaration_order():
    assert SCRIPT_PATH.exists(), f"Missing emitter script: {SCRIPT_PATH}"

    result = _run_emitter()
    assert result.returncode == 0, (
        "emit_field_order.py must succeed in write mode.\n"
        f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
    )
    assert FIELD_ORDER_PATH.exists(), f"Emitter did not write: {FIELD_ORDER_PATH}"

    payload = json.loads(FIELD_ORDER_PATH.read_text(encoding="utf-8"))
    expected_orders = {
        "DealDefinition": list(DealDefinition.model_fields.keys()),
        "BondDef": list(BondDef.model_fields.keys()),
        "RuleNode": list(RuleNode.model_fields.keys()),
        "AccountDef": list(AccountDef.model_fields.keys()),
        "FeeDef": list(FeeDef.model_fields.keys()),
        "TriggerNode": list(TriggerNode.model_fields.keys()),
        "CalculationNode": list(CalculationNode.model_fields.keys()),
        "CollateralGroupDef": list(CollateralGroupDef.model_fields.keys()),
        "TrancheRelation": list(TrancheRelation.model_fields.keys()),
        "RateScheduleEntry": list(RateScheduleEntry.model_fields.keys()),
        "AccountMinimumScheduleEntry": list(AccountMinimumScheduleEntry.model_fields.keys()),
    }

    missing_models = sorted(set(expected_orders) - set(payload))
    assert not missing_models, (
        "field_order.json is missing model entries: "
        + ", ".join(missing_models)
    )

    for model_name, expected in expected_orders.items():
        model_entry = payload[model_name]
        assert "fields" in model_entry, (
            f"{model_name} entry missing 'fields' key"
        )
        actual_names = [f["name"] for f in model_entry["fields"]]
        assert actual_names == expected, (
            f"{model_name} field order drifted.\n"
            f"expected={expected}\n"
            f"actual={actual_names}"
        )
        for field_entry in model_entry["fields"]:
            assert "type" in field_entry, (
                f"{model_name}.{field_entry['name']} missing 'type' key"
            )
            assert isinstance(field_entry["type"], str) and len(field_entry["type"]) > 0, (
                f"{model_name}.{field_entry['name']} type must be a non-empty string"
            )


def test_check_mode_fails_on_drift():
    assert SCRIPT_PATH.exists(), f"Missing emitter script: {SCRIPT_PATH}"
    assert FIELD_ORDER_PATH.exists(), (
        "Expected committed field_order.json to exist before --check drift test."
    )

    original_bytes = FIELD_ORDER_PATH.read_bytes()
    payload = json.loads(original_bytes.decode("utf-8"))
    deal_entry = payload.get("DealDefinition", {})
    deal_fields = deal_entry.get("fields", [])
    assert len(deal_fields) >= 2, "DealDefinition must contain at least two fields."

    # Inject deterministic drift by swapping the first two fields.
    deal_fields[0], deal_fields[1] = deal_fields[1], deal_fields[0]
    payload["DealDefinition"]["fields"] = deal_fields
    FIELD_ORDER_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    try:
        result = _run_emitter("--check")
        assert result.returncode != 0, (
            "--check must fail when committed field_order.json drifts from generated bytes."
        )
        combined = f"{result.stdout}\n{result.stderr}".lower()
        assert (
            "drift" in combined
            or "out of date" in combined
            or "field order" in combined
            or "mismatch" in combined
        ), (
            "Expected clear drift messaging from --check mode.\n"
            f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
        )
    finally:
        FIELD_ORDER_PATH.write_bytes(original_bytes)
